"""YouTube videos linked from source posts: subtitles first, AI viewing second.

Most videos already carry subtitles, uploaded by the channel or generated by YouTube. Reading
them costs no AI quota, and summarising the text with a cheap model costs a few thousand tokens,
where watching a 10-minute video costs about 60,000 (Gemini reads ~100 tokens per second).

1. fetch_transcript(): the video's own subtitles (channel-made before auto-generated; Chinese,
   then English), via youtube-transcript-api. No key. YouTube blocks some cloud IPs: after the
   first block the rest of the run skips straight to step 3.
2. If there are subtitles, the `video_text` role summarises them. When the `video` quota allows,
   a model also watches the video and lists what it shows beyond its words (documents, photos,
   maps, on-screen dates), and says whether the subtitles were enough.
3. No subtitles: the `video` role watches the video, as before.

Every video's outcome is kept in scripts/state/videos.json, so over time we learn how often the
subtitles alone are enough.
"""
import re
from datetime import datetime

import state

LANGS = ["zh-HK", "zh-Hant", "zh-TW", "yue", "zh", "zh-Hans", "zh-CN", "en", "en-GB", "en-US"]
MAX_TRANSCRIPT_CHARS = 40_000  # ~12K tokens; the longest talks are cut, with a note
MARK_EVERY = 30  # seconds between [mm:ss] markers in the text sent to the model
_blocked = False  # set after YouTube refuses this machine; lasts for the run

TRANSCRIPT_PROMPT = """Below are the subtitles ({kind}, language {lang}) of a YouTube video linked from
a Hong Kong history post titled "{title}". [mm:ss] marks the time in the video.
Report what the video says, so a reader who cannot watch it gets the same facts and viewpoints.
Use only the subtitles; auto-generated subtitles can mishear names, so flag names you are unsure of.

Respond with ONLY this JSON:
{{"speaker": "Who presents it (name and role) if stated, else empty",
  "language": "Main spoken language",
  "summary": "200-400 words of markdown in English, third person, attributing claims to the speaker. Use **bold** for key names and dates.",
  "key_points": [{{"time": "mm:ss", "point": "One fact, claim, source or viewpoint stated at that moment"}}],
  "people": ["Name (中文名 if given)"],
  "years": ["1979"]}}

SUBTITLES:
{text}"""

COMPARE_PROMPT = """Watch this video. It is linked from a Hong Kong history post titled "{title}".
We already summarised it from its subtitles:

{summary}

List only what the video shows or says that this summary misses: documents, photographs, maps,
film footage, on-screen text, dates or names that appear on screen, and anything the subtitles
got wrong. Do not repeat what the summary already says.

Respond with ONLY this JSON:
{{"subtitles_enough": true,
  "why": "One sentence: are the subtitles alone enough to report this video's facts?",
  "visual_only": [{{"time": "mm:ss", "what": "What is shown and what it tells us"}}],
  "corrections": ["Something the subtitles or summary got wrong, with the right version"]}}"""


def fetch_transcript(video_id):
    """{"kind": "channel"|"auto-generated", "lang", "segments": [(start_s, text)]}, or
    {"error": reason} when there are none or YouTube refuses."""
    global _blocked
    if _blocked:
        return {"error": "blocked earlier in this run"}
    try:
        from youtube_transcript_api import YouTubeTranscriptApi
    except ImportError:
        return {"error": "youtube-transcript-api not installed"}
    try:
        listing = YouTubeTranscriptApi().list(video_id)
        available = list(listing)
        chosen = None
        for generated in (False, True):  # channel-made subtitles beat auto-generated ones
            for lang in LANGS:
                chosen = next((t for t in available if t.is_generated == generated
                               and t.language_code.lower() == lang.lower()), None)
                if chosen:
                    break
            if chosen:
                break
        chosen = chosen or (available[0] if available else None)
        if not chosen:
            return {"error": "no subtitles"}
        segments = [(float(s.start), s.text.replace("\n", " ").strip()) for s in chosen.fetch()]
        return {"kind": "auto-generated" if chosen.is_generated else "channel",
                "lang": chosen.language_code, "segments": [s for s in segments if s[1]]}
    except Exception as e:
        name = type(e).__name__
        if name in ("IpBlocked", "RequestBlocked"):
            _blocked = True
            print("  [videos] YouTube is blocking subtitle requests from this machine; "
                  "the AI watches videos for the rest of this run")
        return {"error": name}


def transcript_text(segments):
    """Plain text with a [mm:ss] marker every MARK_EVERY seconds, cut to MAX_TRANSCRIPT_CHARS."""
    out, next_mark, size = [], 0, 0
    for start, text in segments:
        if start >= next_mark:
            out.append(f"\n[{int(start) // 60:02d}:{int(start) % 60:02d}]")
            next_mark = start + MARK_EVERY
        out.append(text)
        size += len(text) + 1
        if size > MAX_TRANSCRIPT_CHARS:
            out.append("\n[... subtitles cut here for length ...]")
            break
    return re.sub(r" *\n *", "\n", " ".join(out)).strip()


def record(video_id, **fields):
    data = state.load("videos")
    data[video_id] = {**data.get(video_id, {}), **fields, "date": datetime.now().strftime("%Y-%m-%d")}
    state.save("videos", data)


def stats():
    """How often subtitles existed, and how often the AI found them enough."""
    data = state.load("videos").values()
    compared = [v for v in data if "subtitles_enough" in v]
    return {"videos": len(data),
            "with_subtitles": sum(1 for v in data if v.get("subtitles")),
            "compared": len(compared),
            "subtitles_enough": sum(1 for v in compared if v["subtitles_enough"])}
